import { ROLES } from '../constants/roles.js';

/**
 * Seed data for populating a fresh database with demo medicines, batches,
 * transactions, and users.
 *
 * `_mockId` / `medicineId` / `batchId` values below are the frontend's mock
 * ids (e.g. 'med-001') or batch numbers used purely to cross-reference
 * records during seeding - seed.js resolves them to real ObjectIds and
 * strips them before insertion.
 */

export const medicines = [
  {
    _mockId: 'med-001',
    code: 'AMX-500',
    name: 'Amoxicillin 500mg',
    category: 'Antibiotics',
    manufacturer: 'PharmaCorp Inc.',
    unitType: 'Capsules (bx)',
    unitPrice: 8.5,
    totalStock: 1240,
    reorderLevel: 800,
    storageNotes: 'Store below 25°C, protect from moisture.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 620 },
      { facility: 'Chicago Cold Storage', stock: 480 },
      { facility: 'Seattle West Distribution', stock: 140 },
    ],
    createdAt: '2024-02-10T08:00:00.000Z',
  },
  {
    _mockId: 'med-002',
    code: 'IBU-400',
    name: 'Ibuprofen 400mg',
    category: 'Analgesics',
    manufacturer: 'MediLife Labs',
    unitType: 'Tablets (btl)',
    unitPrice: 5.2,
    totalStock: 85,
    reorderLevel: 200,
    storageNotes: 'Store in a cool, dry place below 30°C.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 40 },
      { facility: 'Chicago Cold Storage', stock: 25 },
      { facility: 'Seattle West Distribution', stock: 20 },
    ],
    createdAt: '2024-03-22T08:00:00.000Z',
  },
  {
    _mockId: 'med-003',
    code: 'LRP-10',
    name: 'Lisinopril 10mg',
    category: 'Cardiovascular',
    manufacturer: 'HeartCare Meds',
    unitType: 'Tablets (bx)',
    unitPrice: 12.75,
    totalStock: 320,
    reorderLevel: 350,
    storageNotes: 'Store below 30°C, protect from light.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 110 },
      { facility: 'Chicago Cold Storage', stock: 90 },
      { facility: 'Seattle West Distribution', stock: 120 },
    ],
    createdAt: '2024-01-05T08:00:00.000Z',
  },
  {
    _mockId: 'med-004',
    code: 'PCM-500',
    name: 'Paracetamol 500mg',
    category: 'Analgesics',
    manufacturer: 'GenericMeds Ltd.',
    unitType: 'Tablets (bx)',
    unitPrice: 3.1,
    totalStock: 5000,
    reorderLevel: 2000,
    storageNotes: 'Store below 25°C.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 2200 },
      { facility: 'Chicago Cold Storage', stock: 1800 },
      { facility: 'Seattle West Distribution', stock: 1000 },
    ],
    createdAt: '2023-11-18T08:00:00.000Z',
  },
  {
    _mockId: 'med-005',
    code: 'CFR-250',
    name: 'Cefuroxime 250mg',
    category: 'Antibiotics',
    manufacturer: 'BioPharma Solutions',
    unitType: 'Suspension (btl)',
    unitPrice: 22.4,
    totalStock: 112,
    reorderLevel: 150,
    storageNotes: 'Refrigerate between 2-8°C. Do not freeze.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 52 },
      { facility: 'Chicago Cold Storage', stock: 35 },
      { facility: 'Seattle West Distribution', stock: 25 },
    ],
    createdAt: '2024-04-02T08:00:00.000Z',
  },
  {
    _mockId: 'med-006',
    code: 'MET-850',
    name: 'Metformin 850mg',
    category: 'Endocrine',
    manufacturer: 'DiabetCare Pharma',
    unitType: 'Tablets (bx)',
    unitPrice: 4.8,
    totalStock: 15000,
    reorderLevel: 5000,
    storageNotes: 'Store below 25°C.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 9000 },
      { facility: 'Chicago Cold Storage', stock: 4000 },
      { facility: 'Seattle West Distribution', stock: 2000 },
    ],
    createdAt: '2024-01-05T08:00:00.000Z',
  },
  {
    _mockId: 'med-007',
    code: 'INS-GLA',
    name: 'Insulin Glargine',
    category: 'Endocrine',
    manufacturer: 'NovaBio Therapeutics',
    unitType: 'Vials (vial)',
    unitPrice: 45,
    totalStock: 2000,
    reorderLevel: 1000,
    storageNotes: 'Refrigerate between 2-8°C. Do not freeze.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 600 },
      { facility: 'Chicago Cold Storage', stock: 1100 },
      { facility: 'Seattle West Distribution', stock: 300 },
    ],
    createdAt: '2024-06-20T08:00:00.000Z',
  },
  {
    _mockId: 'med-008',
    code: 'AZI-250',
    name: 'Azithromycin 250mg',
    category: 'Antibiotics',
    manufacturer: 'PharmaCorp Inc.',
    unitType: 'Tablets (bx)',
    unitPrice: 15.6,
    totalStock: 640,
    reorderLevel: 500,
    storageNotes: 'Store below 25°C.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 300 },
      { facility: 'Chicago Cold Storage', stock: 200 },
      { facility: 'Seattle West Distribution', stock: 140 },
    ],
    createdAt: '2024-05-11T08:00:00.000Z',
  },
  {
    _mockId: 'med-009',
    code: 'INF-23Q',
    name: 'Influenza Vaccine (Quadrivalent)',
    category: 'Vaccines',
    manufacturer: 'ViroShield Biologics',
    unitType: 'Vials (vial)',
    unitPrice: 28.9,
    totalStock: 3200,
    reorderLevel: 1500,
    storageNotes: 'Refrigerate between 2-8°C. Cold chain required.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 1200 },
      { facility: 'Chicago Cold Storage', stock: 1500 },
      { facility: 'Seattle West Distribution', stock: 500 },
    ],
    createdAt: '2024-09-01T08:00:00.000Z',
  },
  {
    _mockId: 'med-010',
    code: 'ALB-INH',
    name: 'Albuterol Inhaler',
    category: 'Respiratory',
    manufacturer: 'PharmaCorp Inc.',
    unitType: 'Inhalers (unit)',
    unitPrice: 18.25,
    totalStock: 410,
    reorderLevel: 600,
    storageNotes: 'Store below 25°C. Do not puncture or incinerate.',
    stockByFacility: [
      { facility: 'Boston Central Hub', stock: 160 },
      { facility: 'Chicago Cold Storage', stock: 130 },
      { facility: 'Seattle West Distribution', stock: 120 },
    ],
    createdAt: '2024-07-19T08:00:00.000Z',
  },
];

export const batches = [
  {
    batchNumber: 'B-7829-X',
    medicineId: 'med-001',
    medicineName: 'Amoxicillin 500mg',
    facility: 'Boston Central Hub',
    quantity: 10000,
    unitType: 'units',
    mfgDate: '2024-10-12',
    expDate: '2027-10-12',
  },
  {
    batchNumber: 'B-4412-Y',
    medicineId: 'med-003',
    medicineName: 'Lisinopril 10mg',
    facility: 'Seattle West Distribution',
    quantity: 5500,
    unitType: 'units',
    mfgDate: '2024-01-15',
    expDate: '2026-01-15',
  },
  {
    batchNumber: 'B-8901-Z',
    medicineId: 'med-007',
    medicineName: 'Insulin Glargine',
    facility: 'Chicago Cold Storage',
    quantity: 2000,
    unitType: 'vials',
    mfgDate: '2025-06-20',
    expDate: '2026-07-20',
  },
  {
    batchNumber: 'B-1123-A',
    medicineId: 'med-006',
    medicineName: 'Metformin 850mg',
    facility: 'Boston Central Hub',
    quantity: 15000,
    unitType: 'units',
    mfgDate: '2024-01-05',
    expDate: '2027-01-05',
  },
  {
    batchNumber: 'B-2309-AX1',
    medicineId: 'med-001',
    medicineName: 'Amoxicillin 500mg',
    facility: 'Chicago Cold Storage',
    quantity: 5000,
    unitType: 'units',
    mfgDate: '2024-09-15',
    expDate: '2027-09-15',
  },
  {
    batchNumber: 'B-5521-P',
    medicineId: 'med-004',
    medicineName: 'Paracetamol 500mg',
    facility: 'Boston Central Hub',
    quantity: 8000,
    unitType: 'bx',
    mfgDate: '2025-03-01',
    expDate: '2028-03-01',
  },
  {
    batchNumber: 'B-9012-C',
    medicineId: 'med-005',
    medicineName: 'Cefuroxime 250mg',
    facility: 'Seattle West Distribution',
    quantity: 300,
    unitType: 'btl',
    mfgDate: '2025-12-01',
    expDate: '2026-07-01',
  },
  {
    batchNumber: 'B-3344-I',
    medicineId: 'med-002',
    medicineName: 'Ibuprofen 400mg',
    facility: 'Chicago Cold Storage',
    quantity: 200,
    unitType: 'btl',
    mfgDate: '2025-01-10',
    expDate: '2026-06-25',
  },
];

export const transactions = [
  {
    type: 'IN',
    medicineId: 'med-003',
    medicineName: 'Lisinopril 10mg Tablets',
    batchId: 'LIS-88A',
    quantity: 2000,
    unitType: 'units',
    date: '2026-06-11T09:42:00.000Z',
    source: 'Global Pharma',
    status: 'Received',
  },
  {
    type: 'IN',
    medicineId: 'med-009',
    medicineName: 'Influenza Vaccine (Quadrivalent)',
    batchId: 'INF-23Q4',
    quantity: 500,
    unitType: 'vials',
    date: '2026-06-10T14:15:00.000Z',
    source: 'Cold Chain Logistics',
    status: 'Received',
    notes: 'Cold chain shipment.',
  },
  {
    type: 'IN',
    medicineId: 'med-002',
    medicineName: 'Ibuprofen Oral Suspension',
    batchId: 'IBU-S-90',
    quantity: 1200,
    unitType: 'bottles',
    date: '2026-06-10T10:05:00.000Z',
    source: 'MedSupply',
    status: 'Received',
  },
  {
    type: 'IN',
    medicineId: 'med-006',
    medicineName: 'Metformin 500mg',
    batchId: 'MET-XX2',
    quantity: 0,
    unitType: 'units',
    date: '2025-10-24T08:30:00.000Z',
    source: 'Damaged In Transit',
    status: 'Rejected',
    notes: 'Shipment rejected - damaged in transit.',
  },
  {
    type: 'OUT',
    medicineId: 'med-004',
    medicineName: 'Paracetamol 500mg',
    batchId: 'B-5521-P',
    quantity: 200,
    unitType: 'units',
    date: '2026-06-11T13:00:00.000Z',
    destination: 'City Clinic',
    status: 'Dispatched',
  },
  {
    type: 'OUT',
    medicineId: 'med-002',
    medicineName: 'Ibuprofen 400mg',
    batchId: 'B-3344-I',
    quantity: 1000,
    unitType: 'units',
    date: '2026-06-10T11:30:00.000Z',
    destination: 'Metro Hospital',
    status: 'Dispatched',
  },
  {
    type: 'OUT',
    medicineId: 'med-001',
    medicineName: 'Amoxicillin 500mg',
    batchId: 'B-7829-X',
    quantity: 750,
    unitType: 'units',
    date: '2026-06-09T09:15:00.000Z',
    destination: 'General Hospital, Sector 4',
    status: 'Dispatched',
  },
  {
    type: 'IN',
    medicineId: 'med-001',
    medicineName: 'Amoxicillin 500mg',
    batchId: 'B-2309-AX1',
    quantity: 5000,
    unitType: 'units',
    date: '2026-06-08T16:20:00.000Z',
    source: 'PharmaCorp Inc.',
    status: 'Received',
  },
];

const now = Date.now();
const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export const users = [
  // Demo login accounts
  {
    name: 'Alex Carter',
    email: 'admin@pharmatrack.com',
    password: 'admin123',
    role: ROLES.ADMIN,
    title: 'System Administrator',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    bio: 'Overseeing global distribution channels for primary synthesized batches.',
    facility: 'HQ - Boston Central Hub',
    status: 'Active',
    lastActiveAt: new Date(now),
  },
  {
    name: 'Maria Gonzalez',
    email: 'manager@pharmatrack.com',
    password: 'manager123',
    role: ROLES.MANAGER,
    title: 'Warehouse Manager',
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    bio: 'Manages day-to-day warehouse operations and stock replenishment.',
    facility: 'Chicago Cold Storage',
    status: 'Active',
    lastActiveAt: new Date(now),
  },
  {
    name: 'James Wilson',
    email: 'staff@pharmatrack.com',
    password: 'staff123',
    role: ROLES.STAFF,
    title: 'Warehouse Staff',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    bio: 'Handles inventory receiving, dispatch, and batch logging.',
    facility: 'Seattle West Distribution',
    status: 'Active',
    lastActiveAt: new Date(now),
  },
  // Directory-only accounts (mirrors userService.js MOCK_DIRECTORY)
  {
    name: 'Sarah Jenkins',
    email: 's.jenkins@pharmatrack.com',
    password: 'changeme123',
    role: ROLES.ADMIN,
    title: 'System Administrator',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    facility: 'HQ - Boston Central Hub',
    status: 'Active',
    lastActiveAt: new Date(now),
  },
  {
    name: 'Marcus Chen',
    email: 'm.chen@pharmatrack.com',
    password: 'changeme123',
    role: ROLES.MANAGER,
    title: 'Warehouse Manager',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    facility: 'Chicago Cold Storage',
    status: 'Active',
    lastActiveAt: new Date(now - 2 * HOUR),
  },
  {
    name: 'Elena Diaz',
    email: 'e.diaz@pharmatrack.com',
    password: 'changeme123',
    role: ROLES.STAFF,
    title: 'Warehouse Staff',
    facility: 'Seattle West Distribution',
    status: 'Inactive',
    lastActiveAt: new Date(now - 5 * DAY),
  },
  {
    name: 'James Wilson',
    email: 'j.wilson@pharmatrack.com',
    password: 'changeme123',
    role: ROLES.STAFF,
    title: 'Warehouse Staff',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    facility: 'Seattle West Distribution',
    status: 'Active',
    lastActiveAt: new Date(now - 1 * DAY),
  },
];
